/**
 * Public exports that expose native Zod schema objects.
 */

export {
  type DeleteAbilityInput,
  type GetAbilityInput,
  type RunAbilityInput,
  WordPressAbilityBuilder,
  type WordPressAbilityRuntime,
} from "./abilities.js";
export {
  type BasicAuthCredentials,
  type CookieNonceAuthCredentials,
  createAuthResolver,
  createBasicAuthHeader,
  createJwtAuthHeader,
  createWordPressAuthHeader,
  type HeaderAuthCredentials,
  type JwtAuthCredentials,
  type JwtAuthTokenResponse,
  type JwtAuthValidationResponse,
  type JwtLoginCredentials,
  type RequestAuthResolver,
  type ResolvableWordPressAuth,
  resolveWordPressAuth,
  resolveWordPressRequestCredentials,
  resolveWordPressRequestHeaders,
  type WordPressAuthConfig,
  type WordPressAuthHeaders,
  type WordPressAuthHeadersProvider,
  type WordPressAuthInput,
  type WordPressAuthorizationInput,
  type WordPressAuthRequest,
  type WordPressAuthResolver,
} from "./auth.js";
export { ContentItemQuery } from "./builders/content-item-query.js";
export { WordPressClient } from "./client.js";
export type { WordPressRawContentResult } from "./content-query.js";
// Embedded data extraction helpers
export {
  ACF_POSTS_EMBED_KEY,
  ACF_TERMS_EMBED_KEY,
  getAcfEmbeddedPosts,
  getAcfEmbeddedTerms,
  getAcfFieldId,
  getAcfFieldIds,
  getAcfFieldPost,
  getAcfFieldPosts,
  getAcfFieldTerms,
  getEmbeddableLinkKeys,
  getEmbeddedAuthor,
  getEmbeddedData,
  getEmbeddedFeaturedMedia,
  getEmbeddedParent,
  getEmbeddedReplies,
  getEmbeddedTerms,
  getLinkEntries,
  type WordPressLinkEntry,
} from "./core/embedded.js";

export {
  classifyFetchError,
  createAuthError,
  createConfigError,
  createDiscoveryError,
  createHttpError,
  createInvalidRequestError,
  createNetworkError,
  createParseError,
  createTimeoutError,
  isWordPressClientError,
  normalizeToClientError,
  type SchemaValidationIssue,
  throwIfHttpError,
  WordPressAuthError,
  WordPressClientError,
  type WordPressClientErrorKind,
  WordPressConfigError,
  WordPressDiscoveryError,
  type WordPressErrorContext,
  type WordPressErrorPayload,
  WordPressHttpError,
  WordPressInvalidRequestError,
  WordPressNetworkError,
  WordPressParseError,
  WordPressTimeoutError,
} from "./core/errors.js";
export {
  createWordPressPaginator,
  type WordPressPaginatorOptions,
} from "./core/pagination.js";

export {
  compactPayload,
  filterToParams,
} from "./core/params.js";
export {
  isStandardSchema,
  type WordPressSchemaIssue,
  type WordPressStandardSchema,
} from "./core/validation.js";
export {
  authorSchema,
  baseWordPressSchema,
  categorySchema,
  commentSchema,
  contentWordPressSchema,
  embeddedMediaSchema,
  jwtAuthErrorResponseSchema,
  jwtAuthTokenResponseSchema,
  jwtAuthValidationResponseSchema,
  mediaSchema,
  pageSchema,
  postLikeWordPressSchema,
  postSchema,
  postWriteBaseSchema,
  searchResultSchema,
  settingsSchema,
  tagSchema,
  updatePostFieldsSchema,
  type WordPressAbility,
  type WordPressAbilityAnnotations,
  type WordPressAbilityCategory,
  type WordPressAuthor,
  type WordPressBase,
  type WordPressCategory,
  type WordPressComment,
  type WordPressContent,
  type WordPressCustomPost,
  type WordPressEmbeddedMedia,
  type WordPressError,
  type WordPressMedia,
  type WordPressPage,
  type WordPressPost,
  type WordPressPostBase,
  type WordPressPostLike,
  type WordPressPostWriteBase,
  type WordPressPostWriteFields,
  type WordPressSearchResult,
  type WordPressSettings,
  type WordPressTag,
  wordPressErrorSchema,
} from "./schemas.js";
export type {
  CategoriesFilter,
  CommentsFilter,
  MediaFilter,
  PagesFilter,
  PostsFilter,
  SearchFilter,
  TagsFilter,
  UsersFilter,
} from "./types/filters.js";
export type {
  ContentResourceClient,
  DeleteOptions,
  FetchResult,
  PaginatedResponse,
  PaginationParams,
  QueryParamPrimitive,
  QueryParams,
  TermsResourceClient,
  TermWriteInput,
  UserDeleteOptions,
  UserWriteInput,
  WordPressClientConfig,
  WordPressDeleteResult,
  WordPressMediaUploadInput,
  WordPressRequestOptions,
  WordPressRequestOverrides,
  WordPressRequestResult,
  WordPressWritePayload,
} from "./types.js";

export {
  type AbilityZodSchemas,
  type ResourceZodSchemas,
  /** @deprecated Prefer `zodFromJsonSchema` for validator conversion. */
  stripDateTimeFormats,
  zodFromJsonSchema,
  zodSchemasFromDescription,
} from "./zod-helpers.js";
